### PR TITLE
update README

### PR DESCRIPTION
**Pull request by retokromer**
- change structure
- update guide

This is the 1<sup>st</sup> step for a variable installation:

- just the general LTO handling tools
- with the database-specific tools
- all, including the CUNY-specific tool

depending on the user’s needs.

### CODE REVIEW

**Comment by retokromer** [comment]
This is preparing https://github.com/amiaopensource/homebrew-amiaos/issues/46.

**Comment by privatezero** [comment]
Hi! I would say that  
* indexschemas
* renameschemas

Are more CUNY specific, rather than DB related

**Comment by retokromer** [comment]
This way?

**Comment by privatezero** [comment]
Oh Sorry! With collectionchecksum also being CUNY specific.

so:
CUNY
* indexschemas
* renameschemas
* collectionchecksum

DB
* ingestschemas
* ingestcollectionchecksum
* searchlto

**Comment by retokromer** [comment]
No problem, it’s easy to modify! ;-)
I have choose alphabetic order.

**Comment by privatezero** [comment]
LGTM!

**Pull request merged**
