### PR TITLE
make version "dynamic"

### PR DESCRIPTION
**Pull request by retokromer**
Thank you @privatezero for the idea!

### CODE REVIEW

**Comment by retokromer** [comment]
@dericed @privatezero If this PR and https://github.com/amiaopensource/ltopers/pull/78 are accepted, should we use the date-based versioning from the next releases on? In my feeling `v2017-03-26` would be more informative than `v0.1.13`.

**Comment by kieranjol** [comment]
How does date versioning handle more than one  update on the same day?

**Comment by retokromer** [comment]
It uses the release information, therefore it would allow to know which release is used. (We never updated nor used really the semantic versioning…)

**Comment by retokromer** [comment]
@kieranjol You can append: `v2017-03-26_patch3_beta2`.

**Comment by dericed** [comment]
Would the results be wrong if the user uses `brew switch` to revert to an earlier version of ltopers. If they did, they would still see the highest numbered installed version number in their help documentation even when they switched to an earlier one.

I'd also suggest a fall back in case a user does not have a `/usr/local/Cellar/ltopers` dir.

**Comment by retokromer** [comment]
Good point!

(In our configuration older/newer versions are automatically removed, and only the last installed is there…)

**Comment by retokromer** [comment]
If we change to date-based versioning, then
```
VERSION=$(brew info ltopers | grep "/ltopers/" | grep -Eo "[0-9]{4}-[0-9]{2}-[0-9]{2}")
```
would give the actual active version.

**Comment by retokromer** [comment]
@dericed This
```
VERSION=$(TMP=$(brew info ltopers | grep -Eo "/ltopers/.* \(") ; echo ${TMP:9:(${#TMP}-11)})
```
should work with any actual installed version.

**Comment by dericed** [comment]
This could also cause confusion when testing an uninstalled script while there is also an installed one, which may be most development scenarios. Could you also add a check to be sure that `dirname $(which "${0}")` is referencing the homebrew installation directory before using the homebrew version number.

**Comment by retokromer** [comment]
Do you mean something like
```
if [[ $(dirname $(which "${0}")) = "/usr/local/bin" ]]; then
  VERSION=$(TMP=$(brew info ltopers | grep -Eo "/ltopers/.* \(") ; echo ${TMP:9:(${#TMP}-11)})
else
  VERSION=""
fi
```
?

**Comment by dericed** [comment]
untested, but yes something like that, so that an uninstalled `mountlto` doesn't provide the version of the installed one

**Comment by retokromer** [comment]
Thank you again! I will amend again.

**Pull request merged**
