### PR TITLE
license documentation

### PR DESCRIPTION
**Pull request by retokromer**
- add CC BY licence
- add version

### CODE REVIEW

**Comment by dericed** [comment]
Noting that this change would require an okay from all contributors represented in the code. Also why CC-BY? It seems overly restrictive to apply in this case. MIT license?

**Comment by retokromer** [comment]
I will change to MIT as soon as I’m again on a normal computer.

**Comment by privatezero** [comment]
I support MIT or BSD 3 Clause!! But consider this me signing off on whatever!

**Comment by retokromer** [comment]
The reason why I don't like MIT is that it's not multilingual, and therefore an exclusive licence. On the contrary, the different CC are a good examples of inclusion. Yet, as said, I'll change to MIT.

**Comment by retokromer** [comment]
Sorry, I could not figure out quickly how to integrate the licence in this PR, therefore I made a separate [commit](https://github.com/amiaopensource/ltopers/commit/7ae4d3e2d7569ac124a342adc43cfe38e2b7c09a).

**Comment by dericed** [comment]
I updated the PR to add the MIT license to this repo.

We need the approval of the current authors to relicense their work. Approval requested from @retokromer, @dericed, @privatezero, @BleakleyMcD, @dinahhandel, @yvonneng, @aeschweik, @CSchloss385, @NMAAHC. Please click https://github.com/amiaopensource/ltopers/pull/138/files and click on 'review changes' to add approval.

**Comment by retokromer** [comment]
@yvonneng is missing, I guess?

**Comment by yvonneng** [comment]
Sorry for the delay. I approve.

**Comment by retokromer** [comment]
Thank you, @yvonneng!
Ping @NMAAHC

**Comment by NMAAHC** [comment]
Approved

**Comment by dericed** [comment]
thx all

**Pull request merged**
