### PR TITLE
ask for info if not provided

### PR DESCRIPTION
**Pull request by dericed**
untested response to https://github.com/amiaopensource/ltopers/issues/169#issuecomment-456555296

### CODE REVIEW

**Comment by kieranjol** [comment]
Yeah,looks like it reflects what's in the current README.

**Comment by retokromer** [comment]
Can this be merged?

**Comment by dericed** [comment]
@retokromer, I'd prefer to wait for the PR to be tested.

**Comment by retokromer** [comment]
@dericed Thank you for the information! I will wait, in order to avoid loosing time by resolving conflicts.

**Comment by retokromer** [comment]
Any news on this one?

**Comment by dericed** [comment]
@retokromer IIUC, this patch is still untested.
Volunteers?

**Comment by retokromer** [comment]
@dericed Reading the code, it looks fine to me. Yet I should be able to set-up a machine and test this week. (I would only have written “Drag-in the directory to write to tape:” (with a dash), but I am not an English native at all.)

**Comment by dericed** [comment]
@retokromer If the status of this pr is blocking you from contributing because of fear of having to resolve conflicts, I suggest to proceed. When tested, if this PR doesn't merge, I'll resolve the conflicts then.

**Comment by retokromer** [comment]
@dericed I’m sorry, I didn’t had the possibility to free a desk for running a test so far.

**Comment by dericed** [comment]
@retokromer, you tested this?

**Comment by retokromer** [comment]
@dericed yep

**Comment by retokromer** [comment]
@dericed Could you possibly made a new release? Then I can update the formula.

**Comment by dericed** [comment]
done

**Comment by retokromer** [comment]
Thanks a lot!

**Pull request merged**
