### PR TITLE
add email function

### PR DESCRIPTION
**Pull request by privatezero**

### CODE REVIEW

**Comment by retokromer** [comment]
I presume, the function uses `sendmail`. I guess, this works fine also on Windows Subsystem for Linux, but will try to check during the weekend.

**Comment by privatezero** [comment]
Yes, it uses `sendmail`.  It is in mmfunctions over here https://github.com/mediamicroservices/mm/blob/master/mmfunctions#L112

**Comment by retokromer** [comment]
Thanks! I’m confident that this works well also on Ubuntu on Windows, but I’ll check in order to be sure.

**Comment by privatezero** [comment]
Oh! I just realized that this is another case of settings that are only integrated into the mm Pashua GUI.  I'll adapt them to the non-Pashua setup as well!

**Comment by retokromer** [comment]
You could add a `DEPENDENCIES=(…)` constant here, which includes `sendmail`.

Somewhere in the documentation we should also add a note on how to configure `sendmail` if not already done on the used computer.

**Comment by retokromer** [comment]
@privatezero FYI: On the Windows Subsystem for Linux `sendmail` is not installed by default. I guess it’s not available as a Brew formula, but for sure it can be installed with `sudo apt-get`. I’ll try to figure out what’s the easiest.

**Comment by privatezero** [comment]
Thank you! I am currently making changes to mmconfig and mmfunctions (this is what the database features rely on for config) so that it only attempts to run/install pashua for macOS, and otherwise will load the CLI interface by default.  Will definitely need some documentation changes as well as the CLI version is much less self descriptive than the GUI!

**Comment by privatezero** [comment]
Changes made in https://github.com/mediamicroservices/mm/pull/147 should enable things to work better when Pashua can't be installed.

**Pull request merged**
