### PR TITLE
no `.DS_Store` onto external storage

### PR DESCRIPTION
**Pull request by retokromer**
should resolve https://github.com/amiaopensource/ltopers/issues/96#issuecomment-301488593

cc @BleakleyMcD

### CODE REVIEW

**Comment by dericed** [comment]
This might cause redundancy. It looks like it runs every time even if it's not needed.

**Comment by retokromer** [comment]
Yes, it runs every time. Of course, we can check the value before and set the variable only if `false`, but it will take more time to run. And it should be set back to the original state after running, as well.

**Comment by retokromer** [comment]
@dericed Now it should overwrite only false with true.

**Comment by dericed** [comment]
Does that test work without quotes. If the key/value is not set the sdtout of the test would be null and I'd except the condition to fail.

**Comment by retokromer** [comment]
Yes, because of the double [[ . . . ]], but I’ll add, it’s probably safer.

**Comment by retokromer** [comment]
This way it works also when I delete completely the variable on my computer, i.e. if macOS is corrupt.

**Pull request merged**
