### PR TITLE
lto_logs change 

### PR DESCRIPTION
**Pull request by BleakleyMcD**
1. changed LTO_LOGS={HOME}/Documents/lto_indexes to LTO_LOGS={LTO_INDEX_DIR} to reflect option in mmconfig
2. moved location of .schema file to schema directory
3. added in {LTO_MD5_FLAGS] to writelto

### CODE REVIEW

**Comment by BleakleyMcD** [comment]
I don't see what the conflict is exactly?

**Comment by dericed** [comment]
conflict resolved

**Comment by retokromer** [comment]
I was doing it…

**Comment by retokromer** [comment]
Thank you, @BleakleyMcD! (and @dericed as well!)

**Pull request merged**
