### PR TITLE
md5deep change 

### PR DESCRIPTION
**Pull request by NMAAHC**
Anyone have a strong preference for -l over -b in md5deep? We find -b makes comparing checksums much easier.

### CODE REVIEW

**Comment by dericed** [comment]
It does but then you lose the context of where the file is. hesitant on this

**Comment by dericed** [comment]
you can adjust the output of -l to the -b style with awk (not well tested):

`md5deep -rl ~/Desktop | awk -F"/" '{print $1 $NF}'`

of compare two outputs like:

```
diff <(cat listA.md5 | awk -F"/" '{print $1 $NF}' | sort -k2) <(cat listB.md5 | awk -F"/" '{print $1 $NF}' | sort -k2)
```

that would compare two check lists without consideration two the directory paths but only to the hash and filename

**Comment by NMAAHC** [comment]
OK. Our directory structures are not particularly complicated so I think we will just invoke Fleetwood Mac and go our own way on this one :)

**Comment by dericed** [comment]
potentially we could make an md5-compare script that accommodates the kind of comparison needed

**Comment by privatezero** [comment]
I totally have not used it so I don't know if this is relevant, but is this the type of thing the hackday 'checksomething' project could help with?

**Pull request closed without merging**
